name: Build and Push Docker Image

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in context
        run: ls -la

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: List public directory in container
        run: |
          docker run --rm ghcr.io/isjustcat/webbedsite:latest ls -la /usr/share/nginx/html



      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/isjustcat/webbedsite:latest
